### PR TITLE
Add view for document with checkboxes

### PR DESCRIPTION
**Pull request by ogomez93**
A recipient landing page that has a document with multiple pages.

There are two checkboxes on the first two pages (so total of four checkboxes).

The user is guided through checking each of those four checkboxes. 

There's a progress bar that shows how many checkboxes they’ve checked (and what’s left).

If the user refreshes the page, they’ll continue where they left off.

If the user submits the document and refreshes the page, they'll start from the beginning.

Documents are only being stored in the database if the user completely fills and submits them.

### CODE REVIEW

**Comment by genericsteele** [comment]
Heyo. Thanks for opening this up. I'll give it a review in the next day or two!

**Comment by ogomez93** [comment]
> Heyo. Thanks for opening this up. I'll give it a review in the next day or two!

Hi, thank you! I hope you like it :)

**Comment by genericsteele** [comment]
Just wanted to give you a heads up that I started my review but didn’t get it finished today. I should be done with this on Monday!

**Comment by ogomez93** [comment]
Hi! Ok, no problem, thanks for the update :)

**Review by genericsteele — APPROVED** [review]
Fantastic job with all this! I'm really struggling to find any changes that need to be made. I'll let Ruben know that I approved it and we'll move forward from there. Thanks so much!

**Comment by ogomez93** [comment]
> Fantastic job with all this! I'm really struggling to find any changes that need to be made. I'll let Ruben know that I approved it and we'll move forward from there. Thanks so much!

Hey! I'm glad you liked what I did. :) I'll be expecting Ruben's message. Thank you!

**Pull request closed without merging**
